- hosts: all
  tasks:
    - name: Install nginx and check latest version
      apt: name=nginx state=latest
    
    - name: start nginx
      service:
          name: nginx
          state: started
    
    - name: Configuration RTMP server (add block at the end of a file)
      blockinfile:
        dest: /etc/nginx/nginx.conf
        block: |
          rtmp {
                server {
                        listen 1935;
                        chunk_size 4096;
                        notify_method get;

                        application live {
                             on_publish http://localhost/auth;
                             live on;
                             record all;
                             record_path /var/www/html/recordings;
                             record_unique on;
                        }
                }
          }
        backup: no
    
    - name: Create directory for recordings
      file:
        path: /etc/records
        state: directory
        owner: www-data
        group: www-data
        mode: 0775
        recurse: yes

    - name: Add a location block to the server configuration
      blockinfile:
        dest: /etc/nginx/sites-enabled/default
        block: |9
                            location /auth {
                                    if ($arg_pwd = 'a_secret_password') {
                                        return 200;
                                        }
                                        return 401;
                            }
        insertafter: server_name _;
        backup: no

    - name: restart nginx 
      service:
        name: nginx
        state: restarted
